SELECT ?OSM_key ?formatter_URL ?rank WHERE {
  { ?item wdt:P1282 ?OSM_key. }
  FILTER(STRSTARTS(?OSM_key, 'Key:')) .

  {
    { ?item p:P1630 [ps:P1630 ?formatter_URL; wikibase:rank ?rank;]. }
    UNION
    { ?item p:P3303[ps:P3303 ?formatter_URL; wikibase:rank ?rank;]. }
  }
}
ORDER BY ?OSM_key ?rank ?formatter_URL
