SELECT ?OSM_key ?formatter_URL ?rank ?source WHERE {
  { ?item wdt:P13786 ?raw_OSM_key. } .

  BIND(CONCAT("Key:", STR( ?raw_OSM_key )) AS ?OSM_key)

  {
    { ?item p:P1630 [ps:P1630 ?formatter_URL; wikibase:rank ?rank;]. BIND("wikidata:P1630" AS ?source ). }
    UNION
    { ?item p:P3303[ps:P3303 ?formatter_URL; wikibase:rank ?rank;]. BIND("wikidata:P3303" AS ?source ). }
  }
  FILTER (?rank != wikibase:DeprecatedRank)
}
ORDER BY ?OSM_key DESC(?rank)
