name: NPM CI build
on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          cache: 'pip'
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: actions/setup-python@v6
        with:
          cache: 'pip'
          python-version: '3.13'
      - run: pip install rdflib requests
      - run: python3 osm_wikidata.py
      - run: npm install
      - run: npm run build
      - run: git diff
      - run: exit $(git diff --numstat | wc -l)

