name: NPM CI build
on:
  - push
  - pull_request

env:
  PYTHON_VERSION: '3.12'
  NODE_VERSION: 20

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: $PYTHON_VERSION
          cache: 'pip'
      - uses: actions/setup-node@v4
        with:
          node-version: $NODE_VERSION
      - run: pip install -r requirements.txt
      - run: python3 osm_wikidata.py
      - run: npm install
      - run: npm run build
      - run: git diff
      - run: exit $(git diff --numstat | wc -l)
