name: NPM CI release
on:
  release:
    types: [created]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          cache: 'pip'
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: pip install rdflib requests
      - run: python3 osm_wikidata.py
      - run: npm install
      - run: npm run build

  publish-npm-registry:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          cache: 'pip'
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: pip install rdflib requests
      - run: python3 osm_wikidata.py
      - run: npm install
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-webjar-test-echo:
    needs: publish-npm-registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo curl "https://www.webjars.org/deploy?webJarType=npm&nameOrUrlish=tag2link&version=$(cat package.json | jq -r '.version')"

