name: NPM CI release
on:
  release:
    types: [created]
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      ref: ${{ steps.ref_finder.outputs.ref }}
    steps:
      - name: Find ref to build/publish
        id: ref_finder
        run: |
          if [[ ! -z "${{ inputs.ref }}" ]]; then echo "ref=${{ inputs.ref }}" >> $GITHUB_OUTPUT
          else echo "ref=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi
      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.ref_finder.outputs.ref }}
      - uses: actions/setup-python@v5
        with:
          cache: 'pip'
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pip install rdflib requests
      - run: python3 osm_wikidata.py
      - run: npm install
      - run: npm run build
      - run: git diff
      - run: exit $(git diff --numstat | wc -l)

  publish-npm-registry-npmjs:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.build.outputs.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish-npm-registry-github:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.build.outputs.ref }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
      - run: |
          sed -i 's+"name": ".*+"name": "@npm.pkg.github.com",+gI' ./package.json
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-webjar:
    needs: publish-npm-registry-npmjs
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.build.outputs.ref }}
      - run: curl "https://www.webjars.org/deploy?webJarType=npm&nameOrUrlish=tag2link&version=$(jq -r '.version' package.json)"

