name: Scheduled update
on:
  schedule:
    - cron: '5 8 21 * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/setup-python@v5
        with:
          cache: 'pip'
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pip install rdflib requests
      - run: python3 osm_wikidata.py
      - run: npm install
      - run: npm run build
      - run: |
          git config --global user.name 'Github tag2link Action'
          git config --global user.email 'tsmock@users.noreply.github.com'
          git commit -am "Automated update"
          git push
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: git tag $(jq -r '.version' package.json) -sm $(jq -r '.version' package.json)
      - run: git push -u origin
      - run: gh release create $(jq -r '.version' package.json) --generate-notes
