name: Scheduled update
on:
  schedule:
    - cron: '5 8 21 * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      sha: ${{ steps.git-push.outputs.sha }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - uses: actions/setup-python@v6
        with:
          cache: 'pip'
          python-version: '3.13'
      - run: pip install rdflib requests
      - run: python3 osm_wikidata.py
      - run: npm install
      - run: npm run build
      - id: git-push
        run: |
          set -ex
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          if ! git diff --cached --quiet; then
            tag=$(jq -r '.version' package.json)
            git commit -m "Automatic update for ${tag}"
            git push origin HEAD:${{ github.ref_name }}
            echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
          else
            echo "No changes."
          fi
        env:
          GH_TOKEN: ${{ github.token }}
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: update
    env:
      GH_TOKEN: ${{ github.token }}
    outputs:
      release_needed: ${{ steps.tag.outputs.release_needed }}
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - id: tag
        run: |
          gh repo sync
          tag=$(git describe --tags --abbrev=0 2>/dev/null) || release_needed="true"
          sha=${{ needs.update.outputs.sha }}
          if [ -z "${sha}" ]; then sha=$(git rev-parse HEAD); fi
          if [ -z "${tag}" ]; then
            release_needed="true"
          else
            for file in $(git diff ${tag}..${sha} --name-only); do
              if [ "$file" == "taginfo.json" ] || [ "$file" == "index.json" ] || [ "$file" == "package.json" ] ; then
                release_needed="true"
                break
              fi
            done
          fi
          if [ "$release_needed" == "true" ]; then
            tag=$(jq -r '.version' package.json)
            gh release create "${tag}" --target "${sha}" --title "${tag}" --generate-notes
            echo "release_needed=true" >> "$GITHUB_OUTPUT"
            echo "tag=${tag}" >> $GITHUB_OUTPUT
          else
            echo "release_needed=false" >> "$GITHUB_OUTPUT"
          fi
  publish:
    needs: tag
    if: needs.tag.outputs.release_needed
    uses: ./.github/workflows/release.yaml
    secrets: inherit
    with:
      ref: ${{ needs.tag.outputs.tag }}
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write
